### PR TITLE
Added support for camunda 7.11 and latest (camunda 7.12)

### PR DESCRIPTION
**Pull request by ieugen**
- added project to support camunda  7.11
- implemented API methods for camunda 7.12 - unreleased

### CODE REVIEW

**Comment by tasso94** [comment]
Hey @martinschimak,

do you have time to look into this contribution?

Cheers,
Tassilo

**Comment by tasso94** [comment]
Hey @ieugen,

the problem you are facing with the Contributor License Agreement is due to the fact, that the user @devlabel-machines is the author of the commit. Only the author of the commit can sign the CLA.

Cheers,
Tassilo

**Comment by ieugen** [comment]
Hi, 
I've fixed that. Tanks for bringing it to my attention.

**Comment by alexanderseik** [comment]
Hi @ieugen,

@martinschimak asked me to review this PR. It will happen within the next two weeks.

Cheers,
Alexander

**Comment by alexanderseik** [comment]
Hi @ieugen 

I reviewed your PR, it looks good!
There are some small details that I would like to change.

-  .gitignore: please revert this. I personally think this is a good change, but it should be in a separate PR.
- In ProcessInstanceDelegateImpl there are formatting changes. Could you please revert them?
- The unit tests you added are a copy of 7.6, please revert this. They are not necessary, because the CI builds should test it with the versions specified. If there are new aspects you want to test, please add a unit test. 

Could you commit these changes in the near future (like in 1 or 2 weeks)? I also could revert the mentioned changes with another PR, if you don't have time for these changes. Just let me know!

I will extend the CI build with another PR, so it will run with newer engine versions.

The CI build of your PR fails, because of Java 6 incompabilites. I talked to @martinschimak, we will remove Java 6 from CI.

Thank you for your PR, it helps a lot!

Cheers,
Alexander

**Comment by martinschimak** [comment]
Merged for some further work to be done by @alexanderseik

**Pull request merged**
